
 --мои тестовые данные
--INSERT INTO users (name, email) VALUES ('Tom', 'Thomas@mail.my');
--INSERT INTO users (name, email) VALUES ('Ben', 'ben@mail.my');
--INSERT INTO users (name, email) VALUES ('Bob', 'bob@mail.my');
--INSERT INTO users (name, email) VALUES ('Bill', 'bill@mail.my');

--INSERT INTO items (name, owner_id, description, available) VALUES ('Hammer', 2, 'Good boat', false);
--INSERT INTO items (name, owner_id, description, available) VALUES ('Saw', 1, 'notBoat', true);
--INSERT INTO items (name, owner_id, description) VALUES ('Boat', 1, 'Fast Boat');

--INSERT INTO booking (item_id, booker_id, start_date, end_date, status) VALUES (1,1, '2023-05-14 01:02:03', '2026-05-14', 'CURRENT');
--INSERT INTO booking (item_id, booker_id, start_date, end_date, status) VALUES (2,2, '2024-01-14 01:02:03', '2027-05-14', 'APPROVED');
--INSERT INTO booking (item_id, booker_id, start_date, end_date, status) VALUES (2,2, '2015-09-14 01:02:03', '2016-05-14', 'rejected');
--INSERT INTO booking (item_id, booker_id, start_date, end_date, status) VALUES (3,2, '2022-09-14 01:02:03', '2027-05-14', 'rejected');

--INSERT INTO comments (item_id, user_id, text) VALUES (1,1,'1Good 1boat');
--INSERT INTO comments (item_id, user_id, text) VALUES (1,2,'2Good 2boat');
--INSERT INTO comments (item_id, user_id, text) VALUES (2,1,'3Good 3boat');
--INSERT INTO comments (item_id, user_id, text) VALUES (2,2,'4Good 4boat');

--comment_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--item_id int REFERENCES items (item_id) ON delete CASCADE,
--user_id int REFERENCES users (user_id) ON delete CASCADE,
--text varchar(200)
--created timestamp without time zone DEFAULT CURRENT_TIMESTAMP


--эту таблицу наверное убрать в итоге так как я добавил в items поле owner_id
--INSERT INTO user_item(user_id, item_id) VALUES (1,1);
--INSERT INTO user_item(user_id, item_id) VALUES (1,2);
--INSERT INTO user_item(user_id, item_id) VALUES (2,3);



